### ISSUE TITLE
TODO: List 

### ISSUE THREAD

**Issue by Zer0xFF** [Thunder07/Play--Framework#1]
- [ ]  replace icu with iconv? Check android support
- [ ] separate input cpp into own library in cmake, directx
- [ ] ? Change Linux settings path ? so that screenshot folder becomes visible
